### ISSUE TITLE
Internals: use a pattern to handle program changes

### ISSUE THREAD

**Issue by fengalin** [fengalin/gstation-edit#32]
When program is modified, it could notify the UI automatically, instead of the UI requesting for an update and applying changes.

**Comment by seve54** [comment]
Good morning! I downloaded: "gtstation-edit-master"! does it work on windows? I am not able!I don't know how to proceed!Thanks!

**Comment by Archloy** [comment]
> Good morning! I downloaded: "gtstation-edit-master"! does it work on windows? I am not able!I don't know how to proceed!Thanks!

Hi ! 
The author said in description : 
> GStation-Edit is a linux replacement for the J-Edit software  

I think, you can download and use J-Edit on windows (or make this software cross-platforms ;) )

**Comment by seve54** [comment]
OK Thanks!

**Comment by Archloy** [comment]
@seve54 : I found an j-station user blog with link to download here : https://mrguitar.net/blog/?p=2068 (on end of post) 
I can't said if it run on newer windows, I think it will need some hacks or virtual machine.

**Comment by fengalin** [comment]
Indeed, `gstation-edit` won't work on Windows as is. Current implementation relies on the [`ALSA`](https://fr.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture) for MIDI communication.

- If you want to configure your J-Station (the device) from Windows, you'd be better off installing `J-Edit` like @Archloy suggested.
- If you want to experiment with the application, you will need a Windows compatible MIDI library in place of `pyAlsa` and adapt [`JStationInterface`](https://github.com/fengalin/gstation-edit/blob/master/gstation_edit/jstation_interface.py) and most classes under the [`midi` module](https://github.com/fengalin/gstation-edit/tree/master/gstation_edit/midi). Also note that the application relies on `gtk-3`, which people usually find challenging to install on Windows.

**Comment by fengalin** [comment]
@seve54: I'm working on another application to control the J-Station and which is aimed at being cross-platform. It's not feature-complete yet like `gstation-edit`, but it can already be used to access all the parameters of the selected Program. All technologies in use are known to be available on the major OSes. Note however that I was only able to test on Linux so far.

The project can be found here: https://github.com/fengalin/jstation-controller

**Comment by fengalin** [comment]
@seve54 & @Archloy: I just released the first version of [`jstation-controller`](https://github.com/fengalin/jstation-controller): a Rust equivalent of J-Edit for linux, macos and Windows with pre-built packages (see the Release page). I could only test on linux so far though. Tell me if you get a chance to give it a try.

**Comment by fengalin** [comment]
Deprecated, use [`jstation-controller`](https://github.com/fengalin/jstation-controller) instead.

**Comment by seve54** [comment]
Good morning! I only tested the one highlighted in red on Windows J-Station: I don't know how to install the other 2. Thank you
![Senza titoloGGH](https://user-images.githubusercontent.com/77013086/211682259-4ab43a7a-8d79-4170-a84a-82ad6f19fb2d.jpg)

**Comment by fengalin** [comment]
@seve54: yes, `jstation-controller-0.1.0.windows-x86_64.zip` is the one you need, I assume you got the others by downloading the sources from the git main branch and the release tag.

Now if you extract `jstation-controller-0.1.0.windows-x86_64.zip`, you will get a folder `jstation-controller-0.1.0.windows-x86_64`. Within this folder, you will find `LICENSES.html` and the application executable `jstation-controller.exe`. Run the executable. If the application switches to the `MIDI Connection` dialog, chances are that your J-Station is not properly hooked up. See this [troubleshooting section](https://github.com/fengalin/gstation-edit#troubleshooting) (I will copy this over to the new repo and add it to the release package).

Note that I didn't get a chance to test it on Windows yet, but given the technologies in use there shouldn't be any major issue. I'll get access to a Windows box tomorrow though so in case it doesn't, I should be able to get it to work diligently.

**Comment by seve54** [comment]
Thank you very much! I look forward to new updates J-Station: good work.

**Comment by fengalin** [comment]
I just published a new [`jstation-controller` release](https://github.com/fengalin/jstation-controller/releases/tag/0.2.0) with minor additions and improvements. And I can confirm the application works as expected on Windows.

**Comment by seve54** [comment]
Good morning! If I may report problems encountered in this conversation:
  1) when you open the app you can also see the windows Dos window below
2) when I select the white theme you don't see the ticks inserted
(see jpg images)
![Senza titolo1](https://user-images.githubusercontent.com/77013086/211982573-85486ae0-00ed-40c1-85d7-9c26b6139975.jpg)
![Senza titolo2jpg](https://user-images.githubusercontent.com/77013086/211982615-51df7674-da87-4f74-86c9-d8d951f9ba78.jpg)
Thanks

**Comment by fengalin** [comment]
Thanks for testing and reporting @seve54! I created issues in [the `jstation-controller` repository](https://github.com/fengalin/jstation-controller/issues).

**Comment by seve54** [comment]
Good morning! With version 02.1 the problems I encountered are solved thanks! Another step "if possible": improve the graphics, I mean with different colors for the various sections: Compressor, Wah, Effect, Amp, , Dealy, Reverb, Cabinet (perhaps with images of the type of cabinet selected). I am attaching png images of the cabinet models from the official editor (J-Edit) which I personally don't like.
Thank you
[Cabinet J Station.zip](https://github.com/fengalin/gstation-edit/files/10416496/Cabinet.J.Station.zip)

**Comment by seve54** [comment]
Good morning! With version 02.1 the problems I encountered are solved thanks! Another step "if possible": improve the graphics, I mean with different colors for the various sections: Compressor, Wah, Effect, Amp, , Dealy, Reverb, Cabinet (perhaps with images of the type of cabinet selected). I am attaching png images of the cabinet models from the official editor. Official J-Edit which I personally don't like.
Thank you
[Cabinet J Station.zip](https://github.com/fengalin/gstation-edit/files/10416501/Cabinet.J.Station.zip)

**Comment by seve54** [comment]
Good morning Fengal! With version 02.1 the problems I encountered have been resolved thanks! Another step "if possible": improve the graphics, I mean with different colors for the various sections: Compressor, Wah, Effect, Amp, , Dealy, Reverb, Cabinet (perhaps with images of the type of cabinet selected). I am attaching png images of the cabinet models from the official editor. Official J-Edit which I personally don't like.
Thank you
[Cabinet J Station.zip](https://github.com/fengalin/gstation-edit/files/10416504/Cabinet.J.Station.zip)

**Comment by seve54** [comment]
Good morning Fengalin
[Cabinet J Station.zip](https://github.com/fengalin/gstation-edit/files/10417143/Cabinet.J.Station.zip)

[Cabinet J Station.zip](https://github.com/fengalin/gstation-edit/files/10417140/Cabinet.J.Station.zip)
in! With version 02.1 the problems I encountered have been resolved thanks! Another step "if possible": improve the graphics, I mean with different colors for the various sections: Compressor, Wah, Effect, Amp, , Dealy, Reverb, Cabinet (perhaps with images of the type of cabinet selected). I am attaching png images of the cabinet models from the official editor. Official J-Edit which I personally don't like.

**Comment by seve54** [comment]
Good morning Fengalin
[Cabinet J Station.zip](https://github.com/fengalin/gstation-edit/files/10417147/Cabinet.J.Station.zip)
! With version 02.1 the problems I encountered have been resolved thanks! Another step "if possible": improve the graphics, I mean with different colors for the various sections: Compressor, Wah, Effect, Amp, , Dealy, Reverb, Cabinet (perhaps with images of the type of cabinet selected). I am attaching png images of the cabinet models from the official editor. Official J-Edit which I personally don't like.

**Comment by seve54** [comment]
Hello Fengalin! With v 02.1 my 2 reports have been resolved: thanks! It would be useful "if possible" to change the various sections with different colors: Compressor, Wah, Effect, Amp, Dealy, Reverb, Cabinet and in the latter perhaps insert the image of the type of cabinet as in the original J-Edit version. I enclose cabinet images.
Thank you
[Cabinet J Station.zip](https://github.com/fengalin/gstation-edit/files/10419958/Cabinet.J.Station.zip)

**Comment by seve54** [comment]
Ok thank you
