### ISSUE TITLE
Failure during installation - Cairo package missing ?! 

### ISSUE THREAD

**Issue by mchch007** [fengalin/gstation-edit#38]
First of all, thanks to fengalin for providing a way to operate my old J-Station under UX. And I am not a programmer :-).

I am facing an issue when trying to set up the environment. The installation stops and terminates with the  output below.
I there any suggestion what I could change or do to  make the installation?

Thanks for any help!

Kind regards

Harald

+++++
Run on

Linux harald-optiplex3060 5.19.0-1009-lowlatency #10-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 20:14:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

+++++
$ pip install --force-reinstall dist/gstation_edit-2.0.3-py3-none-any.whl
Defaulting to user installation because normal site-packages is not writeable
Processing ./dist/gstation_edit-2.0.3-py3-none-any.whl
Collecting pyalsa@ https://github.com/alsa-project/alsa-python/archive/refs/tags/v1.2.7.zip
  Using cached https://github.com/alsa-project/alsa-python/archive/refs/tags/v1.2.7.zip
  Preparing metadata (setup.py) ... done
Collecting pygobject
  Using cached PyGObject-3.42.2.tar.gz (719 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      Collecting setuptools
        Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting pycairo
        Using cached pycairo-1.22.0.tar.gz (342 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: pycairo
        Building wheel for pycairo (pyproject.toml): started
        Building wheel for pycairo (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for pycairo (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-3.10
            creating build/lib.linux-x86_64-3.10/cairo
            copying cairo/__init__.py -> build/lib.linux-x86_64-3.10/cairo
            copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.10/cairo
            copying cairo/py.typed -> build/lib.linux-x86_64-3.10/cairo
            running build_ext
            Package cairo was not found in the pkg-config search path.
            Perhaps you should add the directory containing `cairo.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'cairo' found
            Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
+++++

**Comment by mchch007** [comment]
> First of all, thanks to fengalin for providing a way to operate my old J-Station under UX. And I am not a programmer :-).
> 
> I am facing an issue when trying to set up the environment. The installation stops and terminates with the output below. I there any suggestion what I could change or do to make the installation?
> 
> Thanks for any help!
> 
> Kind regards
> 
> Harald
> 
> +++++ Run on
> 
> Linux harald-optiplex3060 5.19.0-1009-lowlatency #10-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 20:14:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> 
> +++++ $ pip install --force-reinstall dist/gstation_edit-2.0.3-py3-none-any.whl Defaulting to user installation because normal site-packages is not writeable Processing ./dist/gstation_edit-2.0.3-py3-none-any.whl Collecting pyalsa@ https://github.com/alsa-project/alsa-python/archive/refs/tags/v1.2.7.zip Using cached https://github.com/alsa-project/alsa-python/archive/refs/tags/v1.2.7.zip Preparing metadata (setup.py) ... done Collecting pygobject Using cached PyGObject-3.42.2.tar.gz (719 kB) Installing build dependencies ... error error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully. │ exit code: 1 ╰─> [41 lines of output] Collecting setuptools Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB) Collecting wheel Using cached wheel-0.38.4-py3-none-any.whl (36 kB) Collecting pycairo Using cached pycairo-1.22.0.tar.gz (342 kB) Installing build dependencies: started Installing build dependencies: finished with status 'done' Getting requirements to build wheel: started Getting requirements to build wheel: finished with status 'done' Preparing metadata (pyproject.toml): started Preparing metadata (pyproject.toml): finished with status 'done' Building wheels for collected packages: pycairo Building wheel for pycairo (pyproject.toml): started Building wheel for pycairo (pyproject.toml): finished with status 'error' error: subprocess-exited-with-error
> 
> ```
>     × Building wheel for pycairo (pyproject.toml) did not run successfully.
>     │ exit code: 1
>     ╰─> [15 lines of output]
>         running bdist_wheel
>         running build
>         running build_py
>         creating build
>         creating build/lib.linux-x86_64-3.10
>         creating build/lib.linux-x86_64-3.10/cairo
>         copying cairo/__init__.py -> build/lib.linux-x86_64-3.10/cairo
>         copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.10/cairo
>         copying cairo/py.typed -> build/lib.linux-x86_64-3.10/cairo
>         running build_ext
>         Package cairo was not found in the pkg-config search path.
>         Perhaps you should add the directory containing `cairo.pc'
>         to the PKG_CONFIG_PATH environment variable
>         No package 'cairo' found
>         Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
>         [end of output]
>   
>     note: This error originates from a subprocess, and is likely not a problem with pip.
>     ERROR: Failed building wheel for pycairo
>   Failed to build pycairo
>   ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. +++++

Update:

Detected a hint 
https://stackoverflow.com/questions/19298774/package-cairo-was-not-found-in-the-pkg-config-search-path
that helped me to fix the issue with cairo; obviously under ubuntu, package dependencies  had an issue.

Now running into next trap, saying that "alsa/asound.lib.h" is missing. Will continue to grab for a solution to this ....

**Comment by mchch007** [comment]
And another dependency solved, adding package:
     apt-get install libasound2-dev 

Installation is now completed. Issue can be closed. Sorry for bothering, but may be this can be useful as a hint should somebody else encounter similar issues ....

**Comment by fengalin** [comment]
Thank you @mchch007 for reporting (and solving) these issues. Being a programmer, I had those dependencies installed already, so I didn't noticed they were required.

Would you like to submit a Pull Request to update the install procedure?

**Comment by mchch007** [comment]
Hi Francois,

Yes, I think it would be beneficial for "non programmers" like me, and maybe some other musicians, to cope with installation dependencies as much as reasonably possible .

If I need to raise whatever might be needed, please let me know.

Kind regards

Harald (mchch007)

Von meinem Smartphone gesendet

________________________________
Von: François Laignel ***@***.***>
Gesendet: Montag, 28. November 2022, 15:00
An: fengalin/gstation-edit ***@***.***>
Cc: mchch007 ***@***.***>; Mention ***@***.***>
Betreff: Re: [fengalin/gstation-edit] Failure during installation - Cairo package missing ?!  (Issue #38)


Thank you @mchch007<https://github.com/mchch007> for reporting (and solving) these issues. Being a programmer, I had those dependencies installed already, so I didn't noticed they were required.

Would you like to submit a Pull Request to update the install procedure?

**Comment by fengalin** [comment]
@mchch007: you might be interested in my new project [jstation-controller](https://github.com/fengalin/jstation-controller) which replaces `gstation-edit`. See the [release page](https://github.com/fengalin/jstation-controller/releases) which features pre-built versions for Linux, macOS and Windows.

**Comment by mchch007** [comment]
Hi Francois,
thanks for notifying me. Unfortunately, my honeymoon period with the J-Station is over, and I moved to a Canadian VoiceLive3 processor which gives me even more possibilities.
I enjoyed very much working with your software and thank you for your valuable work!
Kind regards,
Harald / @mchch007

Von: François Laignel ***@***.***>
Gesendet: Donnerstag, 12. Januar 2023 00:30
An: fengalin/gstation-edit ***@***.***>
Cc: mchch007 ***@***.***>; Mention ***@***.***>
Betreff: Re: [fengalin/gstation-edit] Failure during installation - Cairo package missing ?! (Issue #38)


@mchch007<https://github.com/mchch007>: you might be interested in my new project jstation-controller<https://github.com/fengalin/jstation-controller> which replaces gstation-edit. See the release page<https://github.com/fengalin/jstation-controller/releases> which features pre-built versions for Linux, macOS and Windows.
